/*!
* Paperview.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
*
* Generated by DuoCode Compiler 2.0.1542.0 [Trial]
*/
(function Paperview_Common() {
"use strict";
var $asm = {
    fullName: "Paperview.Common",
    anonymousTypes: [],
    types: [],
    $getAttrs: function() { return [new System.Reflection.AssemblyTitleAttribute.ctor("Paperview.Common"), new System.Reflection.AssemblyDescriptionAttribute.ctor(""), new System.Reflection.AssemblyConfigurationAttribute.ctor(""), new System.Reflection.AssemblyCompanyAttribute.ctor(""), new System.Reflection.AssemblyProductAttribute.ctor("Paperview.Common"), new System.Reflection.AssemblyCopyrightAttribute.ctor("Copyright \xA9  2015"), new System.Reflection.AssemblyTrademarkAttribute.ctor(""), new System.Reflection.AssemblyCultureAttribute.ctor(""), new System.Reflection.AssemblyVersionAttribute.ctor("1.0.0.0"), new System.Reflection.AssemblyFileVersionAttribute.ctor("1.0.0.0"), new DuoCode.Runtime.CompilerAttribute.ctor("2.0.1542.0")]; }
};
var $g = (typeof(global) !== "undefined" ? global : (typeof(window) !== "undefined" ? window : self));
var Paperview = $g.Paperview = $g.Paperview || {};
Paperview.Common = Paperview.Common || {};
Paperview.Common.Helpers = Paperview.Common.Helpers || {};
var $d = DuoCode.Runtime;
$d.$assemblies["Paperview.Common"] = $asm;
Paperview.Common.Author = $d.declare("Paperview.Common.Author", 0, $asm);
Paperview.Common.DocumentInstanceMetaData = $d.declare("Paperview.Common.DocumentInstanceMetaData", 0, 
    $asm);
Paperview.Common.DocumentTypeMetaData = $d.declare("Paperview.Common.DocumentTypeMetaData", 0, $asm);
Paperview.Common.Helpers.AppStyles = $d.declare("Paperview.Common.Helpers.AppStyles", 0, $asm);
Paperview.Common.Legal = $d.declare("Paperview.Common.Legal", 0, $asm);
Paperview.Common.Publisher = $d.declare("Paperview.Common.Publisher", 0, $asm);
$d.define(Paperview.Common.Author, null, function($t, $p) {
    $t.$intfs = [Paperview.Interfaces.IAuthor, Paperview.Interfaces.IContact];
    $t.$ator = function() {
        this.Id = null;
        this.Name = null;
        this.Email = null;
        this.Url = null;
    };
    $t.ctor = function Author() {
        $t.$baseType.ctor.call(this);
    };
    $t.ctor.prototype = $p;
    $p.get_Id = function Author_get_Id() { return this.Id; };
    $p.set_Id = function Author_set_Id(value) { this.Id = value;return value; };
    $p.get_Name = function Author_get_Name() { return this.Name; };
    $p.set_Name = function Author_set_Name(value) { this.Name = value;return value; };
    $p.get_Email = function Author_get_Email() { return this.Email; };
    $p.set_Email = function Author_set_Email(value) { this.Email = value;return value; };
    $p.get_Url = function Author_get_Url() { return this.Url; };
    $p.set_Url = function Author_set_Url(value) { this.Url = value;return value; };
    $p.Paperview$Interfaces$IContact$get_Id = $p.get_Id;
    $p.Paperview$Interfaces$IContact$set_Id = $p.set_Id;
    $p.Paperview$Interfaces$IContact$get_Name = $p.get_Name;
    $p.Paperview$Interfaces$IContact$set_Name = $p.set_Name;
    $p.Paperview$Interfaces$IContact$get_Email = $p.get_Email;
    $p.Paperview$Interfaces$IContact$set_Email = $p.set_Email;
    $p.Paperview$Interfaces$IContact$get_Url = $p.get_Url;
    $p.Paperview$Interfaces$IContact$set_Url = $p.set_Url;
});
$d.define(Paperview.Common.DocumentInstanceMetaData, null, function($t, $p) {
    $t.$intfs = [Paperview.Interfaces.Shared.IDocumentInstanceMetaData];
    $t.$ator = function() {
        this._originalDocumentInstanceId = null;
        this._documentInstanceId = null;
        this.Legal = null;
        this.Publisher = null;
        this.Author = null;
        this.DocumentInstanceIconBase64 = null;
        this.LanguageAvailability = new (System.Collections.Generic.List$1(String, 40320).ctor)();
        this.LanguageDefault = null;
        this.DocumentInstanceName = new (System.Collections.Generic.Dictionary$2(String, String, 27758).ctor)();
        this.DocumentInstanceDescription = new (System.Collections.Generic.Dictionary$2(String, String, 
            27758).ctor)();
        this.TranspositionHistory = new (System.Collections.Generic.List$1(String, 40320).ctor)();
    };
    $t.ctor = function DocumentInstanceMetaData() {
        $t.$baseType.ctor.call(this);
    };
    $t.ctor.prototype = $p;
    $p.get_Legal = function DocumentInstanceMetaData_get_Legal() { return this.Legal; };
    $p.set_Legal = function DocumentInstanceMetaData_set_Legal(value) { this.Legal = value;return value; };
    $p.get_Publisher = function DocumentInstanceMetaData_get_Publisher() { return this.Publisher; };
    $p.set_Publisher = function DocumentInstanceMetaData_set_Publisher(value) { this.Publisher = value;return value; };
    $p.get_Author = function DocumentInstanceMetaData_get_Author() { return this.Author; };
    $p.set_Author = function DocumentInstanceMetaData_set_Author(value) { this.Author = value;return value; };
    $p.get_OriginalDocumentInstanceId = function DocumentInstanceMetaData_get_OriginalDocumentInstanceId() {
        return this._originalDocumentInstanceId;
    };
    $p.set_OriginalDocumentInstanceId = function DocumentInstanceMetaData_set_OriginalDocumentInstanceId(value) {
        this._originalDocumentInstanceId = value.toLowerCase();
        return value;
    };
    $p.get_DocumentInstanceId = function DocumentInstanceMetaData_get_DocumentInstanceId() {
        return this._documentInstanceId;
    };
    $p.set_DocumentInstanceId = function DocumentInstanceMetaData_set_DocumentInstanceId(value) {
        this._documentInstanceId = value.toLowerCase();
        return value;
    };
    $p.get_DocumentInstanceIconBase64 = function DocumentInstanceMetaData_get_DocumentInstanceIconBase64() { return this.DocumentInstanceIconBase64; };
    $p.set_DocumentInstanceIconBase64 = function DocumentInstanceMetaData_set_DocumentInstanceIconBase64(value) { this.DocumentInstanceIconBase64 = value;return value; };
    $p.get_LanguageAvailability = function DocumentInstanceMetaData_get_LanguageAvailability() { return this.LanguageAvailability; };
    $p.set_LanguageAvailability = function DocumentInstanceMetaData_set_LanguageAvailability(value) { this.LanguageAvailability = value;return value; };
    $p.get_LanguageDefault = function DocumentInstanceMetaData_get_LanguageDefault() { return this.LanguageDefault; };
    $p.set_LanguageDefault = function DocumentInstanceMetaData_set_LanguageDefault(value) { this.LanguageDefault = value;return value; };
    $p.get_DocumentInstanceName = function DocumentInstanceMetaData_get_DocumentInstanceName() { return this.DocumentInstanceName; };
    $p.set_DocumentInstanceName = function DocumentInstanceMetaData_set_DocumentInstanceName(value) { this.DocumentInstanceName = value;return value; };
    $p.get_DocumentInstanceDescription = function DocumentInstanceMetaData_get_DocumentInstanceDescription() { return this.DocumentInstanceDescription; };
    $p.set_DocumentInstanceDescription = function DocumentInstanceMetaData_set_DocumentInstanceDescription(value) { this.DocumentInstanceDescription = value;return value; };
    $p.get_TranspositionHistory = function DocumentInstanceMetaData_get_TranspositionHistory() { return this.TranspositionHistory; };
    $p.set_TranspositionHistory = function DocumentInstanceMetaData_set_TranspositionHistory(value) { this.TranspositionHistory = value;return value; };
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$get_Legal = $p.get_Legal;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$set_Legal = $p.set_Legal;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$get_Publisher = $p.get_Publisher;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$set_Publisher = $p.set_Publisher;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$get_Author = $p.get_Author;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$set_Author = $p.set_Author;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$get_OriginalDocumentInstanceId = $p.get_OriginalDocumentInstanceId;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$set_OriginalDocumentInstanceId = $p.set_OriginalDocumentInstanceId;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$get_DocumentInstanceId = $p.get_DocumentInstanceId;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$set_DocumentInstanceId = $p.set_DocumentInstanceId;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$get_DocumentInstanceIconBase64 = $p.get_DocumentInstanceIconBase64;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$set_DocumentInstanceIconBase64 = $p.set_DocumentInstanceIconBase64;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$get_LanguageAvailability = $p.get_LanguageAvailability;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$set_LanguageAvailability = $p.set_LanguageAvailability;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$get_LanguageDefault = $p.get_LanguageDefault;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$set_LanguageDefault = $p.set_LanguageDefault;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$get_DocumentInstanceName = $p.get_DocumentInstanceName;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$set_DocumentInstanceName = $p.set_DocumentInstanceName;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$get_DocumentInstanceDescription = $p.get_DocumentInstanceDescription;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$set_DocumentInstanceDescription = $p.set_DocumentInstanceDescription;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$get_TranspositionHistory = $p.get_TranspositionHistory;
    $p.Paperview$Interfaces$Shared$IDocumentInstanceMetaData$set_TranspositionHistory = $p.set_TranspositionHistory;
});
$d.define(Paperview.Common.DocumentTypeMetaData, null, function($t, $p) {
    $t.$intfs = [Paperview.Interfaces.IDocumentTypeMetaData];
    $t.$ator = function() {
        this._documentTypeId = null;
        this.Legal = null;
        this.Publisher = null;
        this.Author = null;
        this.DocumentTypeIconBase64 = null;
        this.LanguageAvailability = null;
        this.LanguageDefault = null;
        this.DocumentTypeName = null;
        this.DocumentTypeDescription = null;
    };
    $t.ctor = function DocumentTypeMetaData() {
        $t.$baseType.ctor.call(this);
    };
    $t.ctor.prototype = $p;
    $p.get_Legal = function DocumentTypeMetaData_get_Legal() { return this.Legal; };
    $p.set_Legal = function DocumentTypeMetaData_set_Legal(value) { this.Legal = value;return value; };
    $p.get_Publisher = function DocumentTypeMetaData_get_Publisher() { return this.Publisher; };
    $p.set_Publisher = function DocumentTypeMetaData_set_Publisher(value) { this.Publisher = value;return value; };
    $p.get_Author = function DocumentTypeMetaData_get_Author() { return this.Author; };
    $p.set_Author = function DocumentTypeMetaData_set_Author(value) { this.Author = value;return value; };
    $p.get_DocumentTypeId = function DocumentTypeMetaData_get_DocumentTypeId() {
        return this._documentTypeId;
    };
    $p.set_DocumentTypeId = function DocumentTypeMetaData_set_DocumentTypeId(value) {
        this._documentTypeId = value.toLowerCase();
        return value;
    };
    $p.get_DocumentTypeIconBase64 = function DocumentTypeMetaData_get_DocumentTypeIconBase64() { return this.DocumentTypeIconBase64; };
    $p.set_DocumentTypeIconBase64 = function DocumentTypeMetaData_set_DocumentTypeIconBase64(value) { this.DocumentTypeIconBase64 = value;return value; };
    $p.get_LanguageAvailability = function DocumentTypeMetaData_get_LanguageAvailability() { return this.LanguageAvailability; };
    $p.set_LanguageAvailability = function DocumentTypeMetaData_set_LanguageAvailability(value) { this.LanguageAvailability = value;return value; };
    $p.get_LanguageDefault = function DocumentTypeMetaData_get_LanguageDefault() { return this.LanguageDefault; };
    $p.set_LanguageDefault = function DocumentTypeMetaData_set_LanguageDefault(value) { this.LanguageDefault = value;return value; };
    $p.get_DocumentTypeName = function DocumentTypeMetaData_get_DocumentTypeName() { return this.DocumentTypeName; };
    $p.set_DocumentTypeName = function DocumentTypeMetaData_set_DocumentTypeName(value) { this.DocumentTypeName = value;return value; };
    $p.get_DocumentTypeDescription = function DocumentTypeMetaData_get_DocumentTypeDescription() { return this.DocumentTypeDescription; };
    $p.set_DocumentTypeDescription = function DocumentTypeMetaData_set_DocumentTypeDescription(value) { this.DocumentTypeDescription = value;return value; };
    $p.Paperview$Interfaces$IDocumentTypeMetaData$get_Legal = $p.get_Legal;
    $p.Paperview$Interfaces$IDocumentTypeMetaData$set_Legal = $p.set_Legal;
    $p.Paperview$Interfaces$IDocumentTypeMetaData$get_Publisher = $p.get_Publisher;
    $p.Paperview$Interfaces$IDocumentTypeMetaData$set_Publisher = $p.set_Publisher;
    $p.Paperview$Interfaces$IDocumentTypeMetaData$get_Author = $p.get_Author;
    $p.Paperview$Interfaces$IDocumentTypeMetaData$set_Author = $p.set_Author;
    $p.Paperview$Interfaces$IDocumentTypeMetaData$get_DocumentTypeId = $p.get_DocumentTypeId;
    $p.Paperview$Interfaces$IDocumentTypeMetaData$set_DocumentTypeId = $p.set_DocumentTypeId;
    $p.Paperview$Interfaces$IDocumentTypeMetaData$get_DocumentTypeIconBase64 = $p.get_DocumentTypeIconBase64;
    $p.Paperview$Interfaces$IDocumentTypeMetaData$set_DocumentTypeIconBase64 = $p.set_DocumentTypeIconBase64;
    $p.Paperview$Interfaces$IDocumentTypeMetaData$get_LanguageAvailability = $p.get_LanguageAvailability;
    $p.Paperview$Interfaces$IDocumentTypeMetaData$set_LanguageAvailability = $p.set_LanguageAvailability;
    $p.Paperview$Interfaces$IDocumentTypeMetaData$get_LanguageDefault = $p.get_LanguageDefault;
    $p.Paperview$Interfaces$IDocumentTypeMetaData$set_LanguageDefault = $p.set_LanguageDefault;
    $p.Paperview$Interfaces$IDocumentTypeMetaData$get_DocumentTypeName = $p.get_DocumentTypeName;
    $p.Paperview$Interfaces$IDocumentTypeMetaData$set_DocumentTypeName = $p.set_DocumentTypeName;
    $p.Paperview$Interfaces$IDocumentTypeMetaData$get_DocumentTypeDescription = $p.get_DocumentTypeDescription;
    $p.Paperview$Interfaces$IDocumentTypeMetaData$set_DocumentTypeDescription = $p.set_DocumentTypeDescription;
});
$d.define(Paperview.Common.Helpers.AppStyles, null, function($t, $p) {
    $t.cctor = function() {
        $t.StandardSelectClassKey = "standardSelect";
        $t.StandardOptionClassKey = "standardOption";
    };
});
$d.define(Paperview.Common.Legal, null, function($t, $p) {
    $t.$intfs = [Paperview.Interfaces.ILegal];
    $t.ctor = function Legal() {
        $t.$baseType.ctor.call(this);
    };
    $t.ctor.prototype = $p;
});
$d.define(Paperview.Common.Publisher, null, function($t, $p) {
    $t.$intfs = [Paperview.Interfaces.IPublisher, Paperview.Interfaces.IContact];
    $t.$ator = function() {
        this.Id = null;
        this.Name = null;
        this.Email = null;
        this.Url = null;
    };
    $t.ctor = function Publisher() {
        $t.$baseType.ctor.call(this);
    };
    $t.ctor.prototype = $p;
    $p.get_Id = function Publisher_get_Id() { return this.Id; };
    $p.set_Id = function Publisher_set_Id(value) { this.Id = value;return value; };
    $p.get_Name = function Publisher_get_Name() { return this.Name; };
    $p.set_Name = function Publisher_set_Name(value) { this.Name = value;return value; };
    $p.get_Email = function Publisher_get_Email() { return this.Email; };
    $p.set_Email = function Publisher_set_Email(value) { this.Email = value;return value; };
    $p.get_Url = function Publisher_get_Url() { return this.Url; };
    $p.set_Url = function Publisher_set_Url(value) { this.Url = value;return value; };
    $p.Paperview$Interfaces$IContact$get_Id = $p.get_Id;
    $p.Paperview$Interfaces$IContact$set_Id = $p.set_Id;
    $p.Paperview$Interfaces$IContact$get_Name = $p.get_Name;
    $p.Paperview$Interfaces$IContact$set_Name = $p.set_Name;
    $p.Paperview$Interfaces$IContact$get_Email = $p.get_Email;
    $p.Paperview$Interfaces$IContact$set_Email = $p.set_Email;
    $p.Paperview$Interfaces$IContact$get_Url = $p.get_Url;
    $p.Paperview$Interfaces$IContact$set_Url = $p.set_Url;
});
return $asm;
})();
//# sourceMappingURL=Paperview.Common.js.map
