/*!
* Paperview.Common.Ui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
*
* Generated by DuoCode Compiler 2.0.1542.0 [Trial]
*/
(function Paperview_Common_Ui() {
"use strict";
var $asm = {
    fullName: "Paperview.Common.Ui",
    anonymousTypes: [],
    types: [],
    $getAttrs: function() { return [new System.Reflection.AssemblyTitleAttribute.ctor("Paperview.Common.Ui"), new System.Reflection.AssemblyDescriptionAttribute.ctor(""), new System.Reflection.AssemblyConfigurationAttribute.ctor(""), new System.Reflection.AssemblyCompanyAttribute.ctor(""), new System.Reflection.AssemblyProductAttribute.ctor("Paperview.Common.Ui"), new System.Reflection.AssemblyCopyrightAttribute.ctor("Copyright \xA9  2016"), new System.Reflection.AssemblyTrademarkAttribute.ctor(""), new System.Reflection.AssemblyCultureAttribute.ctor(""), new System.Reflection.AssemblyVersionAttribute.ctor("1.0.0.0"), new System.Reflection.AssemblyFileVersionAttribute.ctor("1.0.0.0"), new DuoCode.Runtime.CompilerAttribute.ctor("2.0.1542.0")]; },
    resources: {
        "Paperview.Common.Ui.Localisation.UiResources$DocumentTypeDescriptionLabel": "Description",
        "Paperview.Common.Ui.Localisation.UiResources$DocumentTypeIdLabel": "Id",
        "Paperview.Common.Ui.Localisation.UiResources$DocumentTypeNameLabel": "Name",
        "Paperview.Common.Ui.Localisation.UiResources$PublisherEmailAddressLabel": "Email Address",
        "Paperview.Common.Ui.Localisation.UiResources$PublisherIdLabel": "Id",
        "Paperview.Common.Ui.Localisation.UiResources$PublisherNameLabel": "Name",
        "Paperview.Common.Ui.Localisation.UiResources$PublisherWebAddressLabel": "Web Address"
    }
};
var $g = (typeof(global) !== "undefined" ? global : (typeof(window) !== "undefined" ? window : self));
var Paperview = $g.Paperview = $g.Paperview || {};
Paperview.Common = Paperview.Common || {};
Paperview.Common.Ui = Paperview.Common.Ui || {};
Paperview.Common.Ui.Helpers = Paperview.Common.Ui.Helpers || {};
Paperview.Common.Ui.Localisation = Paperview.Common.Ui.Localisation || {};
var $d = DuoCode.Runtime;
$d.$assemblies["Paperview.Common.Ui"] = $asm;
Paperview.Common.Ui.Helpers.UiExtensionMethods = $d.declare("Paperview.Common.Ui.Helpers.UiExtensionMethods", 
    0, $asm);
Paperview.Common.Ui.Localisation.UiResources = $d.declare("Paperview.Common.Ui.Localisation.UiResources", 
    0, $asm);
Paperview.Common.Ui.DocumentTypePane = $d.declare("Paperview.Common.Ui.DocumentTypePane", 0, $asm);
Paperview.Common.Ui.PublisherPane = $d.declare("Paperview.Common.Ui.PublisherPane", 0, $asm);
$d.define(Paperview.Common.Ui.Helpers.UiExtensionMethods, null, function($t, $p) {
    $t.AssertLocale = function UiExtensionMethods_AssertLocale(dic, locale, defaultLocale) {
        var response = String.Empty;

        if (dic.ContainsKey(locale)) {
            response = dic.get_Item(locale);
        }
        else {
            response = dic.get_Item(defaultLocale);
        }

        return response;
    };
});
$d.define(Paperview.Common.Ui.Localisation.UiResources, null, function($t, $p) {
    $t.cctor = function() {
        $t.resourceMan = null;
        $t.resourceCulture = null;
    };
    $t.ctor = function UiResources() {
        $t.$baseType.ctor.call(this);
    };
    $t.ctor.prototype = $p;
    $t.get_ResourceManager = function UiResources_get_ResourceManager() {
        if ($t().resourceMan === null) {
            var temp = new System.Resources.ResourceManager.ctor("Paperview.Common.Ui.Localisation.UiResources", 
                $d.typeOf(Paperview.Common.Ui.Localisation.UiResources).get_Assembly());
            $t().resourceMan = temp;
        }
        return $t().resourceMan;
    };
    $t.get_Culture = function UiResources_get_Culture() {
        return $t().resourceCulture;
    };
    $t.set_Culture = function UiResources_set_Culture(value) {
        $t().resourceCulture = value;
        return value;
    };
    $t.get_DocumentTypeDescriptionLabel = function UiResources_get_DocumentTypeDescriptionLabel() {
        return $t().get_ResourceManager().GetString("DocumentTypeDescriptionLabel", $t().resourceCulture);
    };
    $t.get_DocumentTypeIdLabel = function UiResources_get_DocumentTypeIdLabel() {
        return $t().get_ResourceManager().GetString("DocumentTypeIdLabel", $t().resourceCulture);
    };
    $t.get_DocumentTypeNameLabel = function UiResources_get_DocumentTypeNameLabel() {
        return $t().get_ResourceManager().GetString("DocumentTypeNameLabel", $t().resourceCulture);
    };
    $t.get_PublisherEmailAddressLabel = function UiResources_get_PublisherEmailAddressLabel() {
        return $t().get_ResourceManager().GetString("PublisherEmailAddressLabel", $t().resourceCulture);
    };
    $t.get_PublisherIdLabel = function UiResources_get_PublisherIdLabel() {
        return $t().get_ResourceManager().GetString("PublisherIdLabel", $t().resourceCulture);
    };
    $t.get_PublisherNameLabel = function UiResources_get_PublisherNameLabel() {
        return $t().get_ResourceManager().GetString("PublisherNameLabel", $t().resourceCulture);
    };
    $t.get_PublisherWebAddressLabel = function UiResources_get_PublisherWebAddressLabel() {
        return $t().get_ResourceManager().GetString("PublisherWebAddressLabel", $t().resourceCulture);
    };
});
$d.define(Paperview.Common.Ui.DocumentTypePane, null, function($t, $p) {
    $t.$ator = function() {
        this._root = null;
        this._document = null;
        this._locale = null;
        this._divTagKey = "div";
        this._tableTagKey = "table";
        this._tableRowKey = "tr";
        this._tableCellKey = "td";
        this._classAttributeKey = "class";
        this._tableKey = "standardNameValuePairTable";
        this._nameCellClassKey = "standardNamePairCell";
        this._valueCellClassKey = "standardValuePairCell";
    };
    $t.ctor = function DocumentTypePane(root, document, idiom, locale) {
        $t.$baseType.ctor.call(this);
        this._root = root;
        this._document = document;
        this._locale = locale;

        switch (idiom) {
            case 0 /* Idiom.Phone */:
                this.CreateStack();
                break;
            case 1 /* Idiom.Tablet */:
                this.CreateTable();
                break;
            case 2 /* Idiom.Desktop */:
                this.CreateTable();
                break;
            case 3 /* Idiom.Unsupported */:
                this.CreateTable();
                break;
            default:
                throw new System.ArgumentOutOfRangeException.ctor$4("idiom", $d.boxEnum(Paperview.Interfaces.Idiom, 
                    idiom), null);
        }
    };
    $t.ctor.prototype = $p;
    $p.CreateTable = function DocumentTypePane_CreateTable() {
        throw new System.NotImplementedException.ctor();
    };
    $p.CreateStack = function DocumentTypePane_CreateStack() {
        var idLabelElement = document.createElement(this._divTagKey);
        idLabelElement.innerHTML = Paperview.Common.Ui.Localisation.UiResources().get_DocumentTypeIdLabel();
        idLabelElement.setAttribute(this._classAttributeKey, this._nameCellClassKey);
        this._root.appendChild(idLabelElement);

        var idValueElement = document.createElement(this._divTagKey);
        idValueElement.innerHTML = this._document.get_MicroformatId();
        idValueElement.setAttribute(this._classAttributeKey, this._valueCellClassKey);
        this._root.appendChild(idValueElement);

        var nameLabelElement = document.createElement(this._divTagKey);
        nameLabelElement.innerHTML = Paperview.Common.Ui.Localisation.UiResources().get_DocumentTypeNameLabel();
        nameLabelElement.setAttribute(this._classAttributeKey, this._nameCellClassKey);
        this._root.appendChild(nameLabelElement);

        var nameValueElement = document.createElement(this._divTagKey);
        nameValueElement.innerHTML = Paperview.Common.Ui.Helpers.UiExtensionMethods.AssertLocale(this._document.get_MicroformatName(), 
            this._locale, this._document.get_LanguageDefault());
        nameValueElement.setAttribute(this._classAttributeKey, this._valueCellClassKey);
        this._root.appendChild(nameValueElement);

        var descriptionLabelElement = document.createElement(this._divTagKey);
        descriptionLabelElement.innerHTML = Paperview.Common.Ui.Localisation.UiResources().get_DocumentTypeDescriptionLabel();
        descriptionLabelElement.setAttribute(this._classAttributeKey, this._nameCellClassKey);
        this._root.appendChild(descriptionLabelElement);

        var descriptionValueElement = document.createElement(this._divTagKey);
        descriptionValueElement.innerHTML = Paperview.Common.Ui.Helpers.UiExtensionMethods.AssertLocale(this._document.get_MicroformatDescription(), 
            this._locale, this._document.get_LanguageDefault());
        descriptionValueElement.setAttribute(this._classAttributeKey, this._valueCellClassKey);
        this._root.appendChild(descriptionValueElement);
    };
});
$d.define(Paperview.Common.Ui.PublisherPane, null, function($t, $p) {
    $t.$ator = function() {
        this._root = null;
        this._publisher = null;
        this._divTagKey = "div";
        this._tableTagKey = "table";
        this._tableRowKey = "tr";
        this._tableCellKey = "td";
        this._classAttributeKey = "class";
        this._tableKey = "standardNameValuePairTable";
        this._nameCellClassKey = "standardNamePairCell";
        this._valueCellClassKey = "standardValuePairCell";
    };
    $t.ctor = function PublisherPane(root, publisher, idiom) {
        $t.$baseType.ctor.call(this);
        this._root = root;
        this._publisher = publisher;

        switch (idiom) {
            case 0 /* Idiom.Phone */:
                this.CreateStack();
                break;
            case 1 /* Idiom.Tablet */:
                this.CreateTable();
                break;
            case 2 /* Idiom.Desktop */:
                this.CreateTable();
                break;
            case 3 /* Idiom.Unsupported */:
                this.CreateTable();
                break;
            default:
                throw new System.ArgumentOutOfRangeException.ctor$4("idiom", $d.boxEnum(Paperview.Interfaces.Idiom, 
                    idiom), null);
        }
    };
    $t.ctor.prototype = $p;
    $p.CreateStack = function PublisherPane_CreateStack() {

        var idLabelElement = document.createElement(this._divTagKey);
        idLabelElement.innerHTML = Paperview.Common.Ui.Localisation.UiResources().get_PublisherIdLabel();
        idLabelElement.setAttribute(this._classAttributeKey, this._nameCellClassKey);
        this._root.appendChild(idLabelElement);

        var idValueElement = document.createElement(this._divTagKey);
        idValueElement.innerHTML = this._publisher.get_Id();
        idValueElement.setAttribute(this._classAttributeKey, this._valueCellClassKey);
        this._root.appendChild(idValueElement);

        var nameLabelElement = document.createElement(this._divTagKey);
        nameLabelElement.innerHTML = Paperview.Common.Ui.Localisation.UiResources().get_PublisherNameLabel();
        nameLabelElement.setAttribute(this._classAttributeKey, this._nameCellClassKey);
        this._root.appendChild(nameLabelElement);

        var nameValueElement = document.createElement(this._divTagKey);
        nameValueElement.innerHTML = this._publisher.get_Name();
        nameValueElement.setAttribute(this._classAttributeKey, this._valueCellClassKey);
        this._root.appendChild(nameValueElement);

        var emailAddressLabelElement = document.createElement(this._divTagKey);
        emailAddressLabelElement.innerHTML = Paperview.Common.Ui.Localisation.UiResources().get_PublisherEmailAddressLabel();
        emailAddressLabelElement.setAttribute(this._classAttributeKey, this._nameCellClassKey);
        this._root.appendChild(emailAddressLabelElement);

        var emailAddressValueElement = document.createElement(this._divTagKey);
        emailAddressValueElement.innerHTML = this._publisher.get_Email();
        emailAddressValueElement.setAttribute(this._classAttributeKey, this._valueCellClassKey);
        this._root.appendChild(emailAddressValueElement);

        var urlLabelElement = document.createElement(this._divTagKey);
        urlLabelElement.innerHTML = Paperview.Common.Ui.Localisation.UiResources().get_PublisherWebAddressLabel();
        urlLabelElement.setAttribute(this._classAttributeKey, this._nameCellClassKey);
        this._root.appendChild(urlLabelElement);

        var urlValueElement = document.createElement(this._divTagKey);
        urlValueElement.innerHTML = this._publisher.get_Url();
        urlValueElement.setAttribute(this._classAttributeKey, this._valueCellClassKey);
        this._root.appendChild(urlValueElement);
    };
    $p.CreateTable = function PublisherPane_CreateTable() {
        var tableElement = document.createElement(this._tableTagKey);
        tableElement.setAttribute(this._classAttributeKey, this._tableKey);

        var row1Element = document.createElement(this._tableRowKey);

        var idLabelElement = document.createElement(this._tableCellKey);
        idLabelElement.innerHTML = "Id";
        idLabelElement.setAttribute(this._classAttributeKey, this._nameCellClassKey);
        row1Element.appendChild(idLabelElement);

        var idValueElement = document.createElement(this._tableCellKey);
        idValueElement.innerHTML = this._publisher.get_Id();
        idValueElement.setAttribute(this._classAttributeKey, this._valueCellClassKey);
        row1Element.appendChild(idValueElement);

        var row2Element = document.createElement(this._tableRowKey);

        var nameLabelElement = document.createElement(this._tableCellKey);
        nameLabelElement.innerHTML = "Name";
        nameLabelElement.setAttribute(this._classAttributeKey, this._nameCellClassKey);
        row2Element.appendChild((nameLabelElement));

        var nameValueElement = document.createElement(this._tableCellKey);
        nameValueElement.innerHTML = this._publisher.get_Name();
        nameValueElement.setAttribute(this._classAttributeKey, this._valueCellClassKey);
        row2Element.appendChild(nameValueElement);

        var row3Element = document.createElement(this._tableRowKey);

        var emailLabelElement = document.createElement(this._tableCellKey);
        emailLabelElement.innerHTML = "Email";
        emailLabelElement.setAttribute(this._classAttributeKey, this._nameCellClassKey);
        row3Element.appendChild(emailLabelElement);

        var emailValueElement = document.createElement(this._tableCellKey);
        emailValueElement.innerHTML = this._publisher.get_Email();
        emailValueElement.setAttribute(this._classAttributeKey, this._valueCellClassKey);
        row3Element.appendChild(emailValueElement);

        var row4Element = document.createElement(this._tableRowKey);

        var urlLabelElement = document.createElement(this._tableCellKey);
        urlLabelElement.innerHTML = "Web Address";
        urlLabelElement.setAttribute(this._classAttributeKey, this._nameCellClassKey);
        row4Element.appendChild((urlLabelElement));

        var urlValueElement = document.createElement(this._tableCellKey);
        urlValueElement.innerHTML = this._publisher.get_Url();
        urlValueElement.setAttribute(this._classAttributeKey, this._valueCellClassKey);
        row4Element.appendChild(urlValueElement);

        tableElement.appendChild(row1Element);
        tableElement.appendChild(row2Element);
        tableElement.appendChild(row3Element);
        tableElement.appendChild(row4Element);

        this._root.appendChild(tableElement);
    };
});
return $asm;
})();
//# sourceMappingURL=Paperview.Common.Ui.js.map
