/*!
* Type definitions for Paperview.DocumentTypes.Album, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
*
* Generated by DuoCode Compiler 2.0.1542.0 [Trial]
*/

/// <reference path="./mscorlib.d.ts" />
/// <reference path="./Paperview.Common.d.ts" />
/// <reference path="./Paperview.Common.Ui.d.ts" />
/// <reference path="./Paperview.Interfaces.d.ts" />
/// <reference path="./Paperview.Microformats.Album.d.ts" />

declare module Paperview {
    module DocumentTypes {
        module Album {
            // Paperview.DocumentTypes.Album.AlbumApplication
            export interface AlbumApplication extends System.Object {
                _publishers: System.Collections.Generic.List$1<Common.Publisher>;
                _authors: System.Collections.Generic.List$1<Common.Author>;
            }
            export interface AlbumApplicationTypeFunc extends TypeFunction {
                (): AlbumApplicationTypeFunc;
                prototype: AlbumApplication;
                ctor: { new (rootElement: HTMLElement): AlbumApplication; };
            }
            const AlbumApplication: AlbumApplicationTypeFunc;
        }
    }
}
