/*!
* Paperview.DocumentTypes.Album, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
*
* Generated by DuoCode Compiler 2.0.1542.0 [Trial]
*/
(function Paperview_DocumentTypes_Album() {
"use strict";
var $asm = {
    fullName: "Paperview.DocumentTypes.Album",
    anonymousTypes: [],
    types: [],
    $getAttrs: function() { return [new System.Reflection.AssemblyTitleAttribute.ctor("xPaperview"), new System.Reflection.AssemblyDescriptionAttribute.ctor(""), new System.Reflection.AssemblyConfigurationAttribute.ctor(""), new System.Reflection.AssemblyCompanyAttribute.ctor(""), new System.Reflection.AssemblyProductAttribute.ctor("yPaperview"), new System.Reflection.AssemblyCopyrightAttribute.ctor("Copyright \xA9  2016"), new System.Reflection.AssemblyTrademarkAttribute.ctor(""), new System.Reflection.AssemblyCultureAttribute.ctor(""), new System.Reflection.AssemblyVersionAttribute.ctor("1.0.0.0"), new System.Reflection.AssemblyFileVersionAttribute.ctor("1.0.0.0"), new DuoCode.Runtime.CompilerAttribute.ctor("2.0.1542.0")]; }
};
var $g = (typeof(global) !== "undefined" ? global : (typeof(window) !== "undefined" ? window : self));
var Paperview = $g.Paperview = $g.Paperview || {};
Paperview.DocumentTypes = Paperview.DocumentTypes || {};
Paperview.DocumentTypes.Album = Paperview.DocumentTypes.Album || {};
var $d = DuoCode.Runtime;
$d.$assemblies["Paperview.DocumentTypes.Album"] = $asm;
Paperview.DocumentTypes.Album.AlbumApplication = $d.declare("Paperview.DocumentTypes.Album.AlbumApplication", 
    0, $asm);
Paperview.DocumentTypes.Album.Program = $d.declare("Paperview.DocumentTypes.Album.Program", 0, $asm);
$d.define(Paperview.DocumentTypes.Album.AlbumApplication, null, function($t, $p) {
    $t.$ator = function() {
        this._idiom = 0 /* Idiom */;
        this._initialisationJson = null;
        this._albumMicroformat = null;
        this._publishers = null;
        this._selectedPublisherIndex = 0;
        this._selectPublisherAction = null;
        this._authors = null;
        this._selectedauthorIndex = 0;
        this._selectAuthorsAction = null;
        this._rootElement = null;
        this._publisherPane = null;
        this._publisherLabel = null;
        this._dropDownPublishersList = null;
        this._authorLabel = null;
        this._dropDownAuthorsList = null;
    };
    $t.ctor = function AlbumApplication(rootElement, initialisationJson) {
        $t.$baseType.ctor.call(this);
        this._idiom = 0 /* Idiom.Phone */;

        this._rootElement = rootElement;
        this._initialisationJson = initialisationJson;

        // Define the action that will occur when a user selects a publisher
        this._selectPublisherAction = $d.delegate(function(index) {
            this._selectedPublisherIndex = index;
            this._albumMicroformat.get_DocumentInstanceMetaData().set_Publisher(index >= 0 ? this._publishers.get_Item(this._selectedPublisherIndex) : null);
            this._publisherPane.set_Publisher($d.cast(this._albumMicroformat.get_DocumentInstanceMetaData().get_Publisher(), 
                Paperview.Common.Publisher));

            this._publisherLabel.set_Text(index >= 0 ? String.Format("{0} ({1})", [Paperview.Common.Ui.Localisation.UiResources().get_PublisherLabelText(), 
                this._albumMicroformat.get_DocumentInstanceMetaData().get_Publisher().Paperview$Interfaces$IContact$get_Name()]) : Paperview.Common.Ui.Localisation.UiResources().get_PublisherLabelText());
        }, this);

        // Define an action that will occur when a user selects an author
        this._selectAuthorsAction = $d.delegate(function(index) {
            this._selectedauthorIndex = index;
            this._albumMicroformat.get_DocumentInstanceMetaData().set_Author(index >= 0 ? this._authors.get_Item(this._selectedauthorIndex) : null);
            //_authorPane.Author = _albumMicroformat.Author;

            this._authorLabel.set_Text(index >= 0 ? String.Format("{0} ({1})", [Paperview.Common.Ui.Localisation.UiResources().get_AuthorLabelText(), 
                this._albumMicroformat.get_DocumentInstanceMetaData().get_Author().Paperview$Interfaces$IContact$get_Name()]) : Paperview.Common.Ui.Localisation.UiResources().get_AuthorLabelText());
        }, this);

        var microformat = new Paperview.Common.Microformat.ctor();

        //#region 
        // The following describes this specific DocumentType application.
        // The Microformat object above describes the user's specific instance of this Document Type.
        var microformatName = new (System.Collections.Generic.Dictionary$2(String, String, 27758).ctor)();
        microformatName.Add$1("en", "Album");
        microformatName.Add$1("fr", "tbt");
        microformatName.Add$1("de", "tbt");
        microformatName.Add$1("es", "tbt");

        var microformatDescription = new (System.Collections.Generic.Dictionary$2(String, String, 27758).ctor)();
        microformatDescription.Add$1("en", "An Image Album");
        microformatDescription.Add$1("fr", "tbt");
        microformatDescription.Add$1("de", "tbt");
        microformatDescription.Add$1("es", "tbt");

        var document = new Paperview.Common.DocumentTypeMetaData.ctor();
        document.set_DocumentId("1878B000-77ED-417E-BE71-69CBFC716B3C");
        document.set_MicroformatId("1878B000-77ED-417E-BE71-69CBFC716B3C");
        document.set_PresentationId("1878B000-77ED-417E-BE71-69CBFC716B3C");
        document.set_LanguageAvailability(new (System.Collections.Generic.List$1(String, 40320).ctor$1)($d.array(String, 
            ["en", "fr", "de", "es"])));
        document.set_LanguageDefault("en");
        document.set_MicroformatName(microformatName);
        document.set_MicroformatDescription(microformatDescription);
        document.set_Microformat(microformat);

        this._albumMicroformat = (function() {
            var $obj = new Paperview.Microformats.Album.AlbumMicroformat.ctor();
            $obj.set_DocumentTypeMetaData(document);
            return $obj;
        }).call(this);
        //#endregion

        this._publishers = new (System.Collections.Generic.List$1(Paperview.Common.Publisher, 15629).ctor)();

        // ToDo: this is dummy data, waiting for it to be passed across a yet to be create HTML Bridge.
        this._publishers.Add((function() {
            var $obj = new Paperview.Common.Publisher.ctor();
            $obj.set_Id(System.Guid.NewGuid().toString());
            $obj.set_Name("Esperance");
            $obj.set_Email("esperance@xamtastic.com");
            $obj.set_Url("http://www.esperance.chat");
            return $obj;
        }).call(this));

        this._publishers.Add((function() {
            var $obj = new Paperview.Common.Publisher.ctor();
            $obj.set_Id(System.Guid.NewGuid().toString());
            $obj.set_Name("Xamtastic");
            $obj.set_Email("xamtastic@xamtastic.com");
            $obj.set_Url("http://www.xamtastic.com");
            return $obj;
        }).call(this));

        this._publishers.Add((function() {
            var $obj = new Paperview.Common.Publisher.ctor();
            $obj.set_Id(System.Guid.NewGuid().toString());
            $obj.set_Name("Captain Xamtastic");
            $obj.set_Email("thecaptain@captainxamtastic.com");
            $obj.set_Url("http://www.captainxamtastic.com");
            return $obj;
        }).call(this));

        this._authors = new (System.Collections.Generic.List$1(Paperview.Common.Author, 17736).ctor)();

        // ToDo: this is dummy data, waiting for it to be passed across a yet to be create HTML Bridge.
        this._authors.Add((function() {
            var $obj = new Paperview.Common.Author.ctor();
            $obj.set_Id(System.Guid.NewGuid().toString());
            $obj.set_Name("Anthony Harrison");
            $obj.set_Email("anthony.harrison@esperance.chat");
            $obj.set_Url("http://www.esperance.chat");
            return $obj;
        }).call(this));

        this._authors.Add((function() {
            var $obj = new Paperview.Common.Author.ctor();
            $obj.set_Id(System.Guid.NewGuid().toString());
            $obj.set_Name("Anthony Harrison");
            $obj.set_Email("anthony.harrison@xamtastic.com");
            $obj.set_Url("http://www.xamtastic.com");
            return $obj;
        }).call(this));

        this._authors.Add((function() {
            var $obj = new Paperview.Common.Author.ctor();
            $obj.set_Id(System.Guid.NewGuid().toString());
            $obj.set_Name("Captain Xamtastic");
            $obj.set_Email("thecaptain@captainxamtastic.com");
            $obj.set_Url("http://www.captainxamtastic.com");
            return $obj;
        }).call(this));





        //#region Archive (tested)
        // new PublisherPane(rootElement, Idiom.Phone);
        //new PublisherPane(rootElement, publisher, Idiom.Phone);
        //new Panel(rootElement, new PublisherPane(publishers[0], Idiom.Phone).GetContainer(), "Publisher", Idiom.Phone);
        //new DocumentTypePane(rootElement, albumMicroformat.Document, Idiom.Phone, "en");
        //new Panel(rootElement, new DocumentTypePane(albumMicroformat.Document, Idiom.Desktop, "en").GetContainer(), "Document Type", Idiom.Desktop);

        // new DropDownListPane(rootElement, publishers, Idiom.Phone);
        //new Panel(rootElement, new DropDownPublishersListPane(_publishers, _selectPublisherAction, Idiom.Phone).GetContainer(), "Publisher", Idiom.Phone);
        //#endregion

        this.DeclareUi();

        this.LayoutUi();
    };
    $t.ctor.prototype = $p;
    $p.DeclareUi = function AlbumApplication_DeclareUi() {
        var myobj = JSON.parse(this._initialisationJson);
        System.Console.WriteLine$10(myobj.DocumentId);
        this._publisherLabel = (function() {
            var $obj = new Paperview.Common.Ui.LabelPane.ctor$2(Paperview.Common.Ui.Localisation.UiResources().get_PublisherLabelText(), 
                this._idiom);
            $obj.set_TextCase(1 /* TextCase.Upper */);
            return $obj;
        }).call(this);
        this._publisherPane = new Paperview.Common.Ui.PublisherPane.ctor(this._idiom);
        this._dropDownPublishersList = new Paperview.Common.Ui.DropDownPublishersListPane.ctor(this._publishers, 
            this._selectPublisherAction, this._idiom);

        this._authorLabel = (function() {
            var $obj = new Paperview.Common.Ui.LabelPane.ctor$2(Paperview.Common.Ui.Localisation.UiResources().get_AuthorLabelText(), 
                this._idiom);
            $obj.set_TextCase(1 /* TextCase.Upper */);
            return $obj;
        }).call(this);
        this._dropDownAuthorsList = new Paperview.Common.Ui.DropDownAuthorsListPane.ctor(this._authors, 
            this._selectAuthorsAction, this._idiom);
    };
    $p.LayoutUi = function AlbumApplication_LayoutUi() {
        switch (this._idiom) {
            case 0 /* Idiom.Phone */:
                this.LayoutPhone();
                break;
            case 1 /* Idiom.Tablet */:
                this.LayoutTablet();
                break;
            case 2 /* Idiom.Desktop */:
                this.LayoutDesktop();
                break;
            case 3 /* Idiom.Unsupported */:
                break;
            default:
                throw new System.ArgumentOutOfRangeException.ctor();
        }
    };
    $p.LayoutDesktop = function AlbumApplication_LayoutDesktop() {
        Paperview.Common.Ui.Helpers.Hx.AppendChild(this._rootElement, this._publisherLabel.get_Container());
        Paperview.Common.Ui.Helpers.Hx.AppendChild(this._rootElement, this._dropDownPublishersList.get_Container());
        Paperview.Common.Ui.Helpers.Hx.AppendChild(this._rootElement, this._publisherPane.get_Container());
        Paperview.Common.Ui.Helpers.Hx.AppendChild(this._rootElement, this._authorLabel.get_Container());
        Paperview.Common.Ui.Helpers.Hx.AppendChild(this._rootElement, this._dropDownAuthorsList.get_Container());
    };
    $p.LayoutTablet = function AlbumApplication_LayoutTablet() {
        Paperview.Common.Ui.Helpers.Hx.AppendChild(this._rootElement, this._publisherLabel.get_Container());
        Paperview.Common.Ui.Helpers.Hx.AppendChild(this._rootElement, this._dropDownPublishersList.get_Container());
        Paperview.Common.Ui.Helpers.Hx.AppendChild(this._rootElement, this._publisherPane.get_Container());
        Paperview.Common.Ui.Helpers.Hx.AppendChild(this._rootElement, this._authorLabel.get_Container());
        Paperview.Common.Ui.Helpers.Hx.AppendChild(this._rootElement, this._dropDownAuthorsList.get_Container());
    };
    $p.LayoutPhone = function AlbumApplication_LayoutPhone() {
        Paperview.Common.Ui.Helpers.Hx.AppendChild(this._rootElement, this._publisherLabel.get_Container());
        Paperview.Common.Ui.Helpers.Hx.AppendChild(this._rootElement, this._dropDownPublishersList.get_Container());
        Paperview.Common.Ui.Helpers.Hx.AppendChild(this._rootElement, this._publisherPane.get_Container());
        Paperview.Common.Ui.Helpers.Hx.AppendChild(this._rootElement, this._authorLabel.get_Container());
        Paperview.Common.Ui.Helpers.Hx.AppendChild(this._rootElement, this._dropDownAuthorsList.get_Container());
    };
});
$d.define(Paperview.DocumentTypes.Album.Program, null, function($t, $p) {
    $t.Run = function Program_Run(documentTypeDescriptionJson) {
        System.Console.WriteLine$10(documentTypeDescriptionJson);

        var visualroot = document.getElementById("content");
        visualroot.innerHTML = String.Empty;
        var albumApplication = new Paperview.DocumentTypes.Album.AlbumApplication.ctor(visualroot, documentTypeDescriptionJson);
    };
});
return $asm;
})();
//# sourceMappingURL=Paperview.DocumentTypes.Album.js.map
